import { Types } from "mongoose";
import cloudinary from "../config/cloudinary";
import { Subscription } from "../models/subscription.model";
import { Video, VideoVisibility } from "../models/video.model";
import { ApiError } from "../utils/apiError";
import crypto from "crypto";
import { View } from "../models/view.model";
import { Like } from "../models/like.model";

interface ChannelProfile {
  _id: string;
  name: string;
  avatar: string;
  subscribersCount: number;
}

interface UploadVideoPayload {
  videoFile: {
    url: string;
    publicId: string;
  };
  duration: number;
}
interface VideoResult {
  video: {
    id: string;
    title: string;
    description: string;
    thumbnail: string;
    duration: number;
    tags: Array<string>;
    createdAt: Date;
    stats: {
      views: number;
      likesCount: number;
      commentsCount: number;
    };
    channel: ChannelProfile;
  };
  isSubscribed: boolean;
}

// Metadata Payload
interface MetadataPayload {
  title: string;
  description: string;
  category: string;
  tags: string[];
  playlist: string;
  visibility: string;
}

// Get single video service
export const getSingleVideoService = async (
  // get the id's
  videoId: string,
  viewerId?: string
): Promise<VideoResult> => {
  // find the video which is ready and visible and populate channel with it
  const video = await Video.findOne({
    _id: videoId,
    visibility: "PUBLIC",
    status: "READY",
  })
    .select(
      "videoFile title description thumbnail duration tags views likesCount commentsCount channel"
    )
    .populate<{ channel: ChannelProfile }>({
      path: "channel",
      select: "name avatar subscribersCount",
    });
  // check if the video exists or not
  if (!video) {
    throw new ApiError(404, "Video Not Found!");
  }
  // check if the viewer subscribed to this channel or not
  let isSubscribed = false;

  if (viewerId) {
    const subscriptionExists = !!(await Subscription.exists({
      channel: video.channel._id,
      subscriber: viewerId,
    }));

    isSubscribed = subscriptionExists;
  }

  return {
    video: {
      id: video._id.toString(),
      title: video.title,
      description: video.description,
      thumbnail: video.thumbnail?.url ?? "",
      duration: video.duration,
      tags: video.tags,
      createdAt: video.createdAt,
      stats: {
        views: video.views,
        likesCount: video.likesCount,
        commentsCount: video.commentsCount,
      },
      channel: {
        _id: video.channel._id.toString(),
        name: video.channel.name,
        avatar: video.channel.avatar,
        subscribersCount: video.channel.subscribersCount,
      },
    },
    isSubscribed,
  };
};

// Uploading Video
// Get upload signature service
export const getUploadSignatureService = async () => {
  // This signature is generated by Cloudinary SDK
  const timestamp = Math.round(Date.now() / 1000);

  const paramsToSign = {
    timestamp,
    folder: Bun.env.CLOUDINARY_FOLDER,
    resource_type: "videos",
  };

  const signature = cloudinary.utils.api_sign_request(
    paramsToSign,
    Bun.env.CLOUDINARY_API_SECRET as string
  );

  return {
    timestamp,
    signature,
    apiKey: Bun.env.CLOUDINARY_API_KEY,
    cloudName: Bun.env.CLOUDINARY_CLOUD_NAME,
    folder: Bun.env.CLOUDINARY_FOLDER,
  };
};

// create Video record / upload video
export const uploadVideoService = async (
  channelId: string,
  payload: UploadVideoPayload
) => {
  // check if the payload are valid or not
  if (!payload.videoFile.url || !payload.videoFile.publicId) {
    throw new ApiError(400, "Invalid Video File Payload");
  }
  // create the video record in DB but keep the metadata empty
  const createVideoRecord = await Video.create({
    channel: channelId,
    videoFile: {
      url: payload.videoFile.url,
      publicId: payload.videoFile.publicId,
    },
    duration: payload.duration,
    title: "",
    description: "",
    category: "",
    tags: [],
    visibility: "PRIVATE",
    views: 0,
    likesCount: 0,
    commentsCount: 0,
  });
  // return the video
  return createVideoRecord;
};

// Update Metadata Service
export const updateMetadataService = async (
  // get the video and channel Id
  videoId: string,
  channelId: string,
  { title, description, category, tags, playlist, visibility }: MetadataPayload
) => {
  // find the video
  const video = await Video.findOne({
    _id: videoId,
    channel: channelId,
  });
  // check if video exists or
  if (!video) {
    throw new ApiError(404, "Video Not Found!");
  }
  // update the video metadata and save the video
  video.title = title;
  video.description = description;
  video.category = category;
  video.tags = tags;
  video.playlist = new Types.ObjectId(playlist);
  video.visibility = visibility as VideoVisibility;

  await video.save({ validateBeforeSave: false });
  // return the updated video
  return video;
};

// Engagement Services
// Adding view Service
export const addViewService = async (
  videoId: string,
  userId: string | null,
  sessionId: string
) => {
  // check who is the user - is the user logged in or not
  let viewerKey: string = "";

  let newSessionId = null;
  if (userId) {
    viewerKey = `user-${userId}`;
  } else {
    if (!sessionId) {
      sessionId = crypto.randomUUID();
      // set session cookie fro 30 days
      newSessionId = sessionId;
    }
    viewerKey = sessionId;
  }
  // check if the viewer already watched the video or not
  const existingView = await View.findOne({
    viewerKey,
    video: videoId,
  });

  const now = new Date();

  if (!existingView) {
    await View.create({
      viewerKey,
      video: videoId,
      lastCountedAt: now,
    });
    // after crerating view document icrement the vierw count in video
    await Video.findByIdAndUpdate(videoId, { $inc: { views: 1 } });

    return { counted: true, newSessionId };
  }

  const VIEW_WINDOW = 1000 * 60 * 60 * 3;

  const timeDiff = now.getTime() - existingView.lastCountedAt.getTime();

  if (timeDiff > VIEW_WINDOW) {
    existingView.lastCountedAt = now;

    await existingView.save({ validateBeforeSave: false });

    await Video.findByIdAndUpdate(videoId, { $inc: { views: 1 } });

    return { counted: true, newSessionId };
  }

  return { counted: false, newSessionId };
};

// Liking or unliking video
export const toggleLikeService = async (userId: string, videoId: string) => {
  // check if the like already exists or not
  const existingLike = await Like.findOne({
    user: userId,
    video: videoId,
  }).lean();
  // if the video is liked already than delete the like
  if (existingLike) {
    await Like.deleteOne({
      _id: existingLike._id,
    });

    // and update the video likes count
    const unlikeVideo = await Video.findByIdAndUpdate(
      videoId,
      { $inc: { likesCount: -1 } },
      { new: true }
    ).select("likesCount");

    // return the like status and like count
    return {
      liked: false,
      likesCount: unlikeVideo?.likesCount,
    };
  }
  // if video is not liked then add the like
  await Like.create({ user: userId, video: videoId });
  // Then update the like count in video
  const likeVideo = await Video.findByIdAndUpdate(
    videoId,
    { $inc: { likesCount: 1 } },
    { new: true }
  ).select("likesCount");
  // return the like status and like count
  return { liked: true, likesCount: likeVideo?.likesCount };
};
